spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://rahulshendge1496_db_user:Rahul265@cluster0.abcde.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=codecortex_db
